### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by jeanleonino** [yiom/sketchpad#12]

**Comment by Nikitaw99** [comment]
What linter?

**Comment by nihey** [comment]
@Nikitaw99 Probably [eslint](https://github.com/eslint/eslint) or [jshint](https://github.com/jshint/jshint). I've used both and they're very good

**Comment by Nikitaw99** [comment]
@nihey Thanks for pointing it out! I honestly like jshint ;)

**Comment by nihey** [comment]
Duplicate of https://github.com/yiom/sketchpad/issues/3
