### ISSUE TITLE
I already get data object, but cannot redraw/animate/recover in another page

### ISSUE THREAD

**Issue by irgidp** [yiom/sketchpad#45]

**Comment by Thanushkajayasinghe** [comment]
This will help

var settings = strokes;
settings.element = '#sketchpad';
settings.strokes = pass json here
new Sketchpad(settings);

**Comment by irgidp** [comment]
> This will help
> 
> var settings = strokes; settings.element = '#sketchpad'; settings.strokes = pass json here new Sketchpad(settings);

can you help?

in page1.html i try set data object with localStorage.
  var dataObj = sketchpad.toObject()
  window.localStorage.setItem("data", JSON.stringify(dataObj));

in page2.html
 var name = localStorage.getItem("data");

and then?

**Comment by Thanushkajayasinghe** [comment]
page1.html
====================

var sketchpad = new Sketchpad({
  element: '#sketchpad', //  canvas id of page1.html
  width: 300,
  height: 210
});

var sketchPadJson = sketchpad.toJSON();
window.localStorage.setItem("data", JSON.stringify(sketchPadJson));


page2.html
====================

var strokes = JSON.parse(localStorage.getItem("data"));

var settings = strokes ;
settings.element = '#sketchpad'; // canvas id of page2.html
settings.strokes = strokes.strokes ; 
new Sketchpad(settings);
