### ISSUE TITLE
Create Ember Addon

### ISSUE THREAD

**Issue by nihey** [yiom/sketchpad#6]
It may be interesting to write an ember addon based on this library.

**Comment by jeanleonino** [comment]
It may better be a ember-cli addon

**Comment by nihey** [comment]
Sure, i mean't that :). Btw, I think it would be better to do this on another repo. We can link it as a wrapper for this library using ember-cli.

**Comment by jeanleonino** [comment]
Sure thing, the standard for ember-cli addons naming is ember-cli-addon-name. I'll close this issue and wait for the new repo.
